In [1]:
import elevator
import pandas as pd

In [2]:
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)

In [3]:
elev = elevator.Elevator(5)

out = elev.go_to_floor([2, 4], real_time=False)

In [4]:
out

,time_elapsed,current_floor,floors_to_next_dest,time_to_next_dest,next_destination
0,0,5,3,30.0,2
1,1,5,3,29.0,2
2,2,5,3,28.0,2
3,3,5,3,27.0,2
4,4,5,3,26.0,2
5,5,5,3,25.0,2
6,6,5,3,24.0,2
7,7,5,3,23.0,2
8,8,5,3,22.0,2
9,9,5,3,21.0,2
10,10,4,2,20.0,2
11,11,4,2,19.0,2
12,12,4,2,18.0,2
13,13,4,2,17.0,2
14,14,4,2,16.0,2
15,15,4,2,15.0,2
16,16,4,2,14.0,2
17,17,4,2,13.0,2
18,18,4,2,12.0,2
19,19,4,2,11.0,2
20,20,3,1,10.0,2
21,21,3,1,9.0,2
22,22,3,1,8.0,2
23,23,3,1,7.0,2
24,24,3,1,6.0,2
25,25,3,1,5.0,2
26,26,3,1,4.0,2
27,27,3,1,3.0,2
28,28,3,1,2.0,2
29,29,3,1,1.0,2
30,30,2,2,20.0,4
31,31,2,2,19.0,4
32,32,2,2,18.0,4
33,33,2,2,17.0,4
34,34,2,2,16.0,4
35,35,2,2,15.0,4
36,36,2,2,14.0,4
37,37,2,2,13.0,4
38,38,2,2,12.0,4
39,39,2,2,11.0,4
40,40,3,1,10.0,4
41,41,3,1,9.0,4
42,42,3,1,8.0,4
43,43,3,1,7.0,4
44,44,3,1,6.0,4
45,45,3,1,5.0,4
46,46,3,1,4.0,4
47,47,3,1,3.0,4
48,48,3,1,2.0,4
49,49,3,1,1.0,4
50,50,4,<NA>,NaN,<NA>